

package net.shadow.client.helper.event;

public enum EventType {
    PACKET_SEND, PACKET_RECEIVE, ENTITY_RENDER, BLOCK_ENTITY_RENDER, BLOCK_RENDER, MOUSE_EVENT, LORE_QUERY, CONFIG_SAVE, NOCLIP_QUERY, KEYBOARD, POST_INIT, HUD_RENDER, HUD_RENDER_NOMSAA
}
